# SPDX-License-Identifier: AGPL-3.0-or-later
# The blank directives reset only the corresponding vendor commands; all
# other pveproxy.service hardening and dependencies remain intact.
[Service]
ExecStart=
ExecStart=/usr/lib/qsm-pve-direct/pve9-api/qsm-pve-direct-pveproxy start
ExecStop=
ExecStop=/usr/lib/qsm-pve-direct/pve9-api/qsm-pve-direct-pveproxy stop
ExecReload=
ExecReload=/usr/lib/qsm-pve-direct/pve9-api/qsm-pve-direct-pveproxy restart
