# SPDX-License-Identifier: AGPL-3.0-or-later
# The blank directives reset only the corresponding vendor commands; all
# other pveproxy.service hardening and dependencies remain intact.
[Service]
ExecStart=
ExecStart=/usr/lib/q-sunshine/pve9-api/q-sunshine-pveproxy start
ExecStop=
ExecStop=/usr/lib/q-sunshine/pve9-api/q-sunshine-pveproxy stop
ExecReload=
ExecReload=/usr/lib/q-sunshine/pve9-api/q-sunshine-pveproxy restart
