#!/usr/bin/env python3
"""Safely install the q-sunshine Console overlay into a supported PVE 9 UI.

PVE has no stable Web UI plugin API for this placement.  This utility therefore
uses a small, package-owned ``dpkg-divert`` of only ``index.html.tpl``.  The
original file is retained at a fixed diversion path, its exact installed PVE
version and SHA-256 are allow-listed, and an unsupported PVE upgrade is
restored to the untouched stock template rather than patched speculatively.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import re
import stat
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Mapping, Protocol

PACKAGE_NAME = "q-sunshine-pve"
PVE_MANAGER_PACKAGE = "pve-manager"
TEMPLATE_RELATIVE = Path("usr/share/pve-manager/index.html.tpl")
OVERLAY_RELATIVE = Path("usr/share/pve-manager/js/q-sunshine-console.js")
# This was generated by package versions that sent the browser directly to a
# terminal endpoint.  It is never loaded by the current same-origin route,
# but retain its path solely to remove an old package-owned asset on upgrade.
LEGACY_CONFIG_ASSET_RELATIVE = Path("usr/share/pve-manager/js/q-sunshine-console-config.js")
MANIFEST_RELATIVE = Path("usr/share/q-sunshine/pve9-ui/pve-manager-index-template.sha256")
STATE_RELATIVE = Path("var/lib/q-sunshine/pve9-ui/state.json")
DIVERSION_SUFFIX = ".q-sunshine-pve-orig"
MARKER = b"<!-- q-sunshine PVE 9 console overlay; package-managed, do not edit -->\n"
ANCHOR = (
    b'    <script type="text/javascript" '
    b'src="/pve2/js/pvemanagerlib.js?ver=[% version %]"></script>\n'
)
MAX_TEMPLATE_BYTES = 256 * 1024
MAX_SUPPORT_MANIFEST_BYTES = 128 * 1024
_VERSION_PATTERN = re.compile(r"\A[A-Za-z0-9.+:~_-]{1,128}\Z", re.ASCII)
_HASH_PATTERN = re.compile(r"\A[0-9a-f]{64}\Z", re.ASCII)


class UiIntegrationError(RuntimeError):
    """The integration cannot safely change PVE's Web UI."""


class UnsupportedPve(UiIntegrationError):
    """The installed PVE UI is not in the reviewed allow-list."""


class UnsafeUiState(UiIntegrationError):
    """A local file/diversion is not owned by this package as expected."""


@dataclass(frozen=True)
class SupportedTemplate:
    version: str
    sha256: str


@dataclass(frozen=True)
class Paths:
    root: Path

    def under_root(self, relative: Path) -> Path:
        if relative.is_absolute():
            relative = relative.relative_to("/")
        return self.root / relative

    @property
    def template(self) -> Path:
        return self.under_root(TEMPLATE_RELATIVE)

    @property
    def diversion(self) -> Path:
        return Path(f"{self.template}{DIVERSION_SUFFIX}")

    @property
    def overlay(self) -> Path:
        return self.under_root(OVERLAY_RELATIVE)

    @property
    def legacy_config_asset(self) -> Path:
        return self.under_root(LEGACY_CONFIG_ASSET_RELATIVE)

    @property
    def manifest(self) -> Path:
        return self.under_root(MANIFEST_RELATIVE)

    @property
    def state(self) -> Path:
        return self.under_root(STATE_RELATIVE)

class DiversionBackend(Protocol):
    def owner(self, target: Path) -> str | None: ...

    def add(self, target: Path, diverted: Path) -> None: ...

    def remove(self, target: Path, diverted: Path) -> None: ...


class SystemDiversions:
    """The only production path to dpkg's diversion database."""

    def __init__(self, executable: Path = Path("/usr/bin/dpkg-divert")) -> None:
        self._executable = executable

    def _run(self, arguments: list[str]) -> str:
        try:
            completed = subprocess.run(
                [str(self._executable), *arguments],
                stdin=subprocess.DEVNULL,
                stdout=subprocess.PIPE,
                stderr=subprocess.DEVNULL,
                check=False,
                text=True,
                encoding="utf-8",
                errors="replace",
            )
        except OSError as error:
            raise UiIntegrationError("dpkg-divert is unavailable") from error
        if completed.returncode != 0:
            raise UiIntegrationError("dpkg diversion operation failed")
        return completed.stdout.strip()

    def owner(self, target: Path) -> str | None:
        owner = self._run(["--listpackage", str(target)])
        return owner or None

    def add(self, target: Path, diverted: Path) -> None:
        self._run(
            [
                "--package",
                PACKAGE_NAME,
                "--divert",
                str(diverted),
                "--rename",
                "--add",
                str(target),
            ]
        )

    def remove(self, target: Path, diverted: Path) -> None:
        self._run(
            [
                "--package",
                PACKAGE_NAME,
                "--divert",
                str(diverted),
                "--rename",
                "--remove",
                str(target),
            ]
        )


class SandboxDiversions:
    """A file-only diversion backend for isolated source-tree tests.

    It is never selected for the real root filesystem, so test execution
    cannot write the host dpkg diversion database.  Its state marker lives
    under the supplied disposable sysroot.
    """

    def __init__(self, state_path: Path) -> None:
        self._state_path = state_path

    def owner(self, target: Path) -> str | None:
        try:
            value = self._state_path.read_text(encoding="ascii")
        except FileNotFoundError:
            return None
        except OSError as error:
            raise UiIntegrationError("test diversion state is unavailable") from error
        if value != f"{PACKAGE_NAME}\n":
            raise UnsafeUiState("test diversion state is invalid")
        return PACKAGE_NAME

    def add(self, target: Path, diverted: Path) -> None:
        if self.owner(target) is not None or not target.is_file() or diverted.exists():
            raise UiIntegrationError("test diversion operation failed")
        try:
            diverted.parent.mkdir(parents=True, exist_ok=True)
            os.replace(target, diverted)
            self._state_path.parent.mkdir(parents=True, exist_ok=True)
            self._state_path.write_text(f"{PACKAGE_NAME}\n", encoding="ascii")
        except OSError as error:
            raise UiIntegrationError("test diversion operation failed") from error

    def remove(self, target: Path, diverted: Path) -> None:
        if self.owner(target) != PACKAGE_NAME or target.exists() or not diverted.is_file():
            raise UiIntegrationError("test diversion operation failed")
        try:
            os.replace(diverted, target)
            self._state_path.unlink()
        except OSError as error:
            raise UiIntegrationError("test diversion operation failed") from error


def _read_regular(path: Path, *, maximum: int, require_root_owner: bool) -> bytes:
    flags = os.O_RDONLY | getattr(os, "O_CLOEXEC", 0) | getattr(os, "O_NOFOLLOW", 0)
    try:
        descriptor = os.open(path, flags)
    except OSError as error:
        raise UnsafeUiState("required PVE UI file is unavailable") from error
    try:
        metadata = os.fstat(descriptor)
        if (
            not stat.S_ISREG(metadata.st_mode)
            or metadata.st_mode & (stat.S_IWGRP | stat.S_IWOTH)
            or (require_root_owner and metadata.st_uid != 0)
            or metadata.st_size < 0
            or metadata.st_size > maximum
        ):
            raise UnsafeUiState("required PVE UI file is unsafe")
        chunks: list[bytes] = []
        remaining = maximum + 1
        while remaining:
            chunk = os.read(descriptor, min(65536, remaining))
            if not chunk:
                break
            chunks.append(chunk)
            remaining -= len(chunk)
        data = b"".join(chunks)
        if len(data) > maximum:
            raise UnsafeUiState("required PVE UI file is too large")
        return data
    finally:
        os.close(descriptor)


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def load_supported_templates(path: Path, *, require_root_owner: bool) -> dict[str, SupportedTemplate]:
    try:
        content = _read_regular(
            path,
            maximum=MAX_SUPPORT_MANIFEST_BYTES,
            require_root_owner=require_root_owner,
        ).decode("ascii")
    except UnicodeDecodeError as error:
        raise UnsafeUiState("PVE UI compatibility manifest is invalid") from error
    supported: dict[str, SupportedTemplate] = {}
    for line in content.splitlines():
        if not line or line.startswith("#"):
            continue
        fields = line.split("\t")
        if len(fields) != 2 or not _VERSION_PATTERN.fullmatch(fields[0]) or not _HASH_PATTERN.fullmatch(fields[1]):
            raise UnsafeUiState("PVE UI compatibility manifest is invalid")
        version, digest = fields
        if version in supported:
            raise UnsafeUiState("PVE UI compatibility manifest is invalid")
        supported[version] = SupportedTemplate(version=version, sha256=digest)
    if not supported:
        raise UnsafeUiState("PVE UI compatibility manifest is invalid")
    return supported


def render_patched_template(original: bytes, overlay_digest: str) -> bytes:
    """Inject the Console asset with a content-addressed browser cache key."""
    if MARKER in original or original.count(ANCHOR) != 1:
        raise UnsupportedPve("PVE Web UI layout is unsupported")
    if _HASH_PATTERN.fullmatch(overlay_digest) is None:
        raise UnsafeUiState("q-sunshine Console overlay digest is invalid")
    injected = (
        ANCHOR
        + MARKER
        + b'    <script type="text/javascript" src="/pve2/js/q-sunshine-console.js?ver=[% version %]-qsm-overlay-'
        + overlay_digest[:16].encode("ascii")
        + b'"></script>\n'
    )
    return original.replace(ANCHOR, injected, 1)


def _assert_safe_parent(path: Path, *, require_root_owner: bool) -> None:
    try:
        metadata = path.lstat()
    except OSError as error:
        raise UnsafeUiState("PVE UI directory is unavailable") from error
    if (
        not stat.S_ISDIR(metadata.st_mode)
        or metadata.st_mode & (stat.S_IWGRP | stat.S_IWOTH)
        or (require_root_owner and metadata.st_uid != 0)
    ):
        raise UnsafeUiState("PVE UI directory is unsafe")


def _atomic_write(path: Path, content: bytes, *, mode: int, require_root_owner: bool) -> None:
    _assert_safe_parent(path.parent, require_root_owner=require_root_owner)
    descriptor, temporary_name = tempfile.mkstemp(prefix=".q-sunshine-", dir=path.parent)
    temporary = Path(temporary_name)
    try:
        os.fchmod(descriptor, mode)
        if require_root_owner:
            os.fchown(descriptor, 0, 0)
        offset = 0
        while offset < len(content):
            written = os.write(descriptor, content[offset:])
            if written <= 0:
                raise OSError("short write")
            offset += written
        os.fsync(descriptor)
        os.close(descriptor)
        descriptor = -1
        os.replace(temporary, path)
        directory_descriptor = os.open(path.parent, os.O_RDONLY | getattr(os, "O_DIRECTORY", 0))
        try:
            os.fsync(directory_descriptor)
        finally:
            os.close(directory_descriptor)
    except OSError as error:
        raise UiIntegrationError("cannot update PVE Web UI integration") from error
    finally:
        if descriptor >= 0:
            os.close(descriptor)
        try:
            temporary.unlink()
        except FileNotFoundError:
            pass


def _unlink_managed(path: Path, *, marker: bytes, require_root_owner: bool) -> bool:
    try:
        os.lstat(path)
    except FileNotFoundError:
        return False
    except OSError as error:
        raise UnsafeUiState("required PVE UI file is unavailable") from error
    data = _read_regular(path, maximum=MAX_TEMPLATE_BYTES, require_root_owner=require_root_owner)
    if marker not in data:
        raise UnsafeUiState("refusing to remove an unmanaged PVE UI file")
    try:
        path.unlink()
    except OSError as error:
        raise UiIntegrationError("cannot remove PVE Web UI integration") from error
    return True


def _default_package_version() -> str:
    try:
        completed = subprocess.run(
            ["/usr/bin/dpkg-query", "-W", "-f=${db:Status-Status}\t${Version}", PVE_MANAGER_PACKAGE],
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            check=False,
            text=True,
            encoding="utf-8",
            errors="replace",
        )
    except OSError as error:
        raise UnsupportedPve("pve-manager is unavailable") from error
    if completed.returncode != 0:
        raise UnsupportedPve("pve-manager is unavailable")
    fields = completed.stdout.strip().split("\t", 1)
    if len(fields) != 2 or fields[0] != "installed" or not _VERSION_PATTERN.fullmatch(fields[1]):
        raise UnsupportedPve("pve-manager is unavailable")
    return fields[1]


class UiIntegration:
    """Stateful, conservative PVE Web UI overlay manager."""

    def __init__(
        self,
        paths: Paths,
        diversions: DiversionBackend,
        *,
        package_version: Callable[[], str] = _default_package_version,
        require_root_owner: bool = True,
    ) -> None:
        self.paths = paths
        self.diversions = diversions
        self.package_version = package_version
        self.require_root_owner = require_root_owner

    def _supported_original(self) -> tuple[SupportedTemplate, Path, bytes]:
        version = self.package_version()
        supported = load_supported_templates(
            self.paths.manifest,
            require_root_owner=self.require_root_owner,
        ).get(version)
        if supported is None:
            raise UnsupportedPve("installed pve-manager version is not supported")
        owner = self.diversions.owner(self.paths.template)
        if owner is None:
            original_path = self.paths.template
        elif owner == PACKAGE_NAME:
            original_path = self.paths.diversion
        else:
            raise UnsafeUiState("PVE Web UI template has another diversion")
        original = _read_regular(
            original_path,
            maximum=MAX_TEMPLATE_BYTES,
            require_root_owner=self.require_root_owner,
        )
        if _sha256(original) != supported.sha256:
            raise UnsupportedPve("installed PVE Web UI template hash is not supported")
        return supported, original_path, original

    def _check_overlay_asset(self) -> str:
        # The static overlay is package-owned; allow only a safe regular file
        # before adding a template reference to it.
        content = _read_regular(
            self.paths.overlay,
            maximum=MAX_TEMPLATE_BYTES,
            require_root_owner=self.require_root_owner,
        )
        if not content.startswith(b"/*\n * q-sunshine Console menu integration"):
            raise UnsafeUiState("q-sunshine Console overlay is invalid")
        # PVE's own version field does not change when just this package is
        # upgraded.  Tie the browser URL to the actual immutable payload so a
        # normal PVE page reload cannot reuse an older Console implementation.
        return _sha256(content)

    def _write_state(self, supported: SupportedTemplate) -> None:
        self.paths.state.parent.mkdir(parents=True, exist_ok=True)
        try:
            os.chmod(self.paths.state.parent, 0o700)
            if self.require_root_owner:
                os.chown(self.paths.state.parent, 0, 0)
        except OSError as error:
            raise UiIntegrationError("cannot prepare PVE UI integration state") from error
        state = json.dumps(
            {
                "pve_manager_version": supported.version,
                "template_sha256": supported.sha256,
                "version": 2,
            },
            sort_keys=True,
            separators=(",", ":"),
        ).encode("ascii") + b"\n"
        _atomic_write(
            self.paths.state,
            state,
            mode=0o600,
            require_root_owner=self.require_root_owner,
        )

    def _remove_state(self) -> None:
        try:
            self.paths.state.unlink()
        except FileNotFoundError:
            pass
        except OSError as error:
            raise UiIntegrationError("cannot remove PVE UI integration state") from error

    def _remove_legacy_config_asset(self) -> None:
        try:
            _unlink_managed(
                self.paths.legacy_config_asset,
                marker=b"/* q-sunshine generated endpoint map; public metadata only. */\n",
                require_root_owner=self.require_root_owner,
            )
        except FileNotFoundError:
            pass

    def _refresh_diverted(self) -> None:
        supported, _original_path, original = self._supported_original()
        try:
            current = _read_regular(
                self.paths.template,
                maximum=MAX_TEMPLATE_BYTES,
                require_root_owner=self.require_root_owner,
            )
        except UnsafeUiState as error:
            raise UnsafeUiState("q-sunshine PVE UI diversion is incomplete") from error
        if current.count(MARKER) != 1:
            raise UnsafeUiState("refusing to overwrite an unmanaged PVE UI template")
        overlay_digest = self._check_overlay_asset()
        self._remove_legacy_config_asset()
        _atomic_write(
            self.paths.template,
            render_patched_template(original, overlay_digest),
            mode=0o644,
            require_root_owner=self.require_root_owner,
        )
        self._write_state(supported)

    def install(self) -> None:
        owner = self.diversions.owner(self.paths.template)
        if owner == PACKAGE_NAME:
            self._refresh_diverted()
            return
        if owner is not None:
            raise UnsafeUiState("PVE Web UI template has another diversion")

        supported, _original_path, original = self._supported_original()
        overlay_digest = self._check_overlay_asset()
        self._remove_legacy_config_asset()
        self.diversions.add(self.paths.template, self.paths.diversion)
        try:
            diverted = _read_regular(
                self.paths.diversion,
                maximum=MAX_TEMPLATE_BYTES,
                require_root_owner=self.require_root_owner,
            )
            if diverted != original:
                raise UnsafeUiState("PVE Web UI diversion changed its source unexpectedly")
            _atomic_write(
                self.paths.template,
                render_patched_template(diverted, overlay_digest),
                mode=0o644,
                require_root_owner=self.require_root_owner,
            )
            self._write_state(supported)
        except BaseException:
            # A failed first install must leave PVE's stock template available.
            try:
                self._restore_diversion()
            except UiIntegrationError:
                pass
            raise

    def _restore_diversion(self) -> None:
        owner = self.diversions.owner(self.paths.template)
        if owner != PACKAGE_NAME:
            if owner is None:
                return
            raise UnsafeUiState("PVE Web UI template has another diversion")
        patched: bytes | None = None
        try:
            patched = _read_regular(
                self.paths.template,
                maximum=MAX_TEMPLATE_BYTES,
                require_root_owner=self.require_root_owner,
            )
        except UnsafeUiState:
            if self.paths.template.exists():
                raise
        if patched is not None:
            if MARKER not in patched:
                raise UnsafeUiState("refusing to remove an unmanaged PVE UI template")
            try:
                self.paths.template.unlink()
            except OSError as error:
                raise UiIntegrationError("cannot remove PVE Web UI integration") from error
        try:
            self.diversions.remove(self.paths.template, self.paths.diversion)
        except UiIntegrationError:
            # dpkg-divert must see an absent target before it can restore the
            # diverted stock file. If that database operation fails, put the
            # exact previous managed template back so pveproxy never serves a
            # missing index.html.tpl.
            if patched is not None:
                try:
                    _atomic_write(
                        self.paths.template,
                        patched,
                        mode=0o644,
                        require_root_owner=self.require_root_owner,
                    )
                except UiIntegrationError:
                    pass
            raise
        self._remove_state()

    def remove(self) -> None:
        self._restore_diversion()
        self._remove_legacy_config_asset()

    def reconcile(self) -> str:
        """Reapply a reviewed update, or safely restore stock PVE on mismatch."""
        try:
            owner = self.diversions.owner(self.paths.template)
            if owner is None:
                self.install()
                return "installed"
            if owner != PACKAGE_NAME:
                raise UnsafeUiState("PVE Web UI template has another diversion")
            self._refresh_diverted()
            return "refreshed"
        except UnsupportedPve:
            # During a pve-manager upgrade this is the important behavior: the
            # PVE package's new template is restored untouched and the custom
            # entry disappears until q-sunshine ships a reviewed hash row.
            self._restore_diversion()
            self._remove_legacy_config_asset()
            return "disabled-unsupported-pve"

    def status(self) -> str:
        owner = self.diversions.owner(self.paths.template)
        if owner == PACKAGE_NAME:
            return "active"
        if owner is None:
            return "inactive"
        return "foreign-diversion"


def _parse_arguments(arguments: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("command", choices=("install", "reconcile", "remove", "status"))
    parser.add_argument(
        "--root",
        type=Path,
        default=Path("/"),
        help=argparse.SUPPRESS,
    )
    parser.add_argument(
        "--package-version",
        help=argparse.SUPPRESS,
    )
    return parser.parse_args(arguments)


def main(arguments: list[str] | None = None) -> int:
    parsed = _parse_arguments(sys.argv[1:] if arguments is None else arguments)
    root = parsed.root.resolve()
    testing_root = root != Path("/")
    if parsed.command != "status" and not testing_root and os.geteuid() != 0:
        print("q-sunshine PVE UI: must run as root", file=sys.stderr)
        return 2
    if parsed.package_version is not None and not testing_root:
        print("q-sunshine PVE UI: --package-version is test-only", file=sys.stderr)
        return 2
    version = (lambda: parsed.package_version) if parsed.package_version is not None else _default_package_version
    diversions: DiversionBackend
    if testing_root:
        diversions = SandboxDiversions(root / "var/lib/q-sunshine/pve9-ui/test-diversion-owner")
    else:
        diversions = SystemDiversions()
    integration = UiIntegration(
        Paths(root),
        diversions,
        package_version=version,
        require_root_owner=not testing_root,
    )
    try:
        if parsed.command == "install":
            integration.install()
            outcome = "installed"
        elif parsed.command == "reconcile":
            outcome = integration.reconcile()
        elif parsed.command == "remove":
            integration.remove()
            outcome = "removed"
        else:
            outcome = integration.status()
    except UiIntegrationError as error:
        print(f"q-sunshine PVE UI: {error}", file=sys.stderr)
        return 1
    print(f"q-sunshine PVE UI: {outcome}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
